# Generated by Django 4.2.11 on 2025-05-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_mute', models.BooleanField(default=False)),
                ('chat_block', models.BooleanField(default=False)),
                ('is_chat_pin_set', models.BooleanField(default=False)),
                ('chat_pin', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_setting_action_by_set', to=settings.AUTH_USER_MODEL)),
                ('action_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_setting_action_for_set', to=settings.AUTH_USER_MODEL)),
                ('chat_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_setting_config_set', to='chat.chatconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participant_config_set', to='chat.chatconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participant_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
