# Generated by Django 4.2.11 on 2025-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsetting_chatparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='chat_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
